# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:

 - stage: Build
   jobs:
   - job: Build
     steps:
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'moveFile'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      - task: DownloadBuildArtifacts@1
        inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

    
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            Stop-Service -Name 'CaptureService_124a74'
            Stop-WebAppPool -Name 'RightAngle21.0AppPool'
            

      - task: WindowsMachineFileCopy@2
        displayName: 'Copy files'
        inputs:
            SourcePath: '$(System.DefaultWorkingDirectory)/_prpalank12.move/drop/App.config'
            MachineNames: 52.183.141.200
            AdminUserName: 'vc_candidate11'
            AdminPassword: 'eSlY8U#8#5p4'
            TargetPath: 'C:\Users\TEMP\Desktop'
